landmark_choices = {
  'a': 'The Kremlin and Red Square',
  'b': 'Pushkin State Museum of Fine Arts',
  'c': 'State Historical Museum',
  'd': 'Tretyakov Gallery',
  'e': 'Izmailovsky Park',
  'f': 'Arbat',
  'g': 'Cathedral of Christ the Saviour',
  'h': 'Luzhniki Stadium',
  'i': 'Krymskiy Bridge',
  'j': 'Zaryad\'ye Park',
  'k': 'Nikulin\'s Circus',
  'l': 'Muzeon Park of Arts',
  'm': 'Gorky Park',
  'n': 'Moscow Zoo',
  'o': 'Moscow State University',
  'p': 'Moscow City',
  'q': 'Izmailovo Kremlin',
  'r': 'Bolshoi Theatre',
  's': 'VDNKH',
  't': 'Donskoy Monastery',
  'u': 'Novodevichiy Monastery',
  'v': 'Ostankino Tower',
  'w': 'Tsaritsyno Palace',
  'x': 'Vinzavod',
  'y': 'National Centre for Contemporary Arts',
  'z': 'State Darwin Museum'
}
