mos_landmarks = {
  'The Kremlin and Red Square': {'Okhotnyi Ryad', 'Biblioteka im. Lenina', 'Aleksandrovskiy Sad', 'Borovitskaya'},
  'Pushkin State Museum of Fine Arts': {'Kropotkinskaya', 'Borovitskaya'},
  'State Historical Museum': {'Okhotnyi Ryad', 'Biblioteka im. Lenina', 'Aleksandrovskiy Sad', 'Borovitskaya',
                              'Teatral\'naya', 'Ploschad\' Revolutsii'},
  'Tretyakov Gallery': {'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)', 'Polyanka'},
  'Izmailovsky Park': {'Sokolinaya Gora (MCC)', 'Partizanskaya', 'Izmailovo (MCC)', 'Izmailovskaya'},
  'Arbat': {'Smolenskaya (Arbatsko-Pokrovskaya Line)', 'Arbatskaya (Filevskaya Line)'},
  'Cathedral of Christ the Saviour': {'Kropotkinskaya'},
  'Luzhniki Stadium': {'Vorob\'yevy Gory', 'Sportivnaya', 'Luzhniki (MCC)'},
  'Krymskiy Bridge': {'Park Kul\'tury (Ring Line)', 'Park Kul\'tury'},
  'Zaryad\'ye Park': {'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)', 'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)'},
  'Nikulin\'s Circus': {'Tsvetnoi Blvd.', 'Trubnaya'},
  'Muzeon Park of Arts': {'Oktyabrskaya', 'Oktyabrskaya (Ring Line)'},
  'Gorky Park': {'Oktyabrskaya', 'Oktyabrskaya (Ring Line)'},
  'Moscow Zoo': {'Barrikadnaya', 'Krasnopresnenskaya'},
  'Moscow State University': {'Vorob\'yevy Gory', 'Universitet', 'Lomonosovskiy Prospekt'},
  'Moscow City': {'Vystavochnaya', 'Mezhdunarodnaya', 'Delovoy Tsentr'},
  'Izmailovo Kremlin': {'Partizanskaya', 'Izmailovo (MCC)'},
  'Bolshoi Theatre': {'Teatral\'naya', 'Okhotnyi Ryad'},
  'VDNKH': {'VDNKH'},
  'Donskoy Monastery': {'Shabolovskaya', 'Leninskiy Prospekt'},
  'Novodevichiy Monastery': {'Sportivnaya'},
  'Ostankino Tower': {'VDNKH'},
  'Tsaritsyno Palace': {'Tsaritsyno', 'Tsaritsyno (D2)', 'Orekhovo'},
  'Vinzavod': {'Kurskaya (Ring Line)', 'Chkalovskaya'},
  'National Centre for Contemporary Arts': {'Barrikadnaya', 'Krasnopresnenskaya'},
  'State Darwin Museum': {'Akademicheskaya'}
}
