moscow_subway = {
    'Aviamotornaya (Kalininskaya Line)': {'Shosse Entuziastov', 'Ploschad\' Il\'icha',
                                          'Aviamotornaya (Nekrasovskaya Line)'},
    'Aviamotornaya (Nekrasovskaya Line)': {'Aviamotornaya (Kalininskaya Line)', 'Lefortovo', 'Nizhegorodskaya'},
    'Avtozavodskaya': {'Paveletskaya (Zamoskvoretskaya Line)', 'Technopark', 'Avtozavodskaya (MCС)'},
    'Avtozavodskaya (MCС)': {'Avtozavodskaya', 'Dubrovka (MCC)', 'ZIL (MCC)'},
    'Akademicheskaya': {'Leninskiy Prospekt', 'Profsoyuznaya'},
    'Aleksandrovskiy Sad': {'Biblioteka im. Lenina', 'Arbatskaya (Filevskaya Line)',
                            'Borovitskaya', 'Arbatskaya (Arbatsko-Pokrovskaya Line)'},
    'Alekseevskaya': {'Rizhskaya', 'VDNKH'},
    'Alma-Atinskaya': {'Krasnogvardeiskaya'},
    'Altufyevo': {'Bibirevo'},
    'Amin\'yevskaya (BCC)': {'Davydkovo (BCC)', 'Michurinskiy Prospekt (BCC)'},
    'Andronovka (MCC)': {'Nizhegorodskaya (MCC)', 'Shosse Entuziastov (MCC)'},
    'Anikeevka (D2)': {'Nakhabino (D2)', 'Opalikha (D2)'},
    'Annino': {'Ul. Akademika Yangelya', 'Bvd. Dmitriya Donskogo'},
    'Arbatskaya (Arbatsko-Pokrovskaya Line)': {'Borovitskaya', 'Biblioteka im. Lenina', 'Aleksandrovskiy Sad',
                                               'Ploschad\' Revolutsii', 'Smolenskaya (Arbatsko-Pokrovskaya Line)'},
    'Arbatskaya (Filevskaya Line)': {'Aleksandrovskiy Sad', 'Smolenskaya (Filevskaya Line)'},
    'Aeroport': {'Dynamo', 'Sokol'},
    'Babushkinskaya': {'Medvedkovo', 'Sviblovo'},
    'Bagrationovskaya': {'Filevskiy Park', 'Fili (Filevskaya Line)'},
    'Bakovka (D1)': {'Odintsovo (D1)', 'Skolkovo (D1)'},
    'Baltiyskaya (MCC)': {'Voikovskaya', 'Koptevo (MCC)', 'Streshnevo (MCC)'},
    'Barrikadnaya': {'Krasnopresnenskaya', 'Pushkinskaya', 'Ul. 1905 Goda'},
    'Baumanskaya': {'Elektrozavodskaya (Arbatsko-Pokrovskaya Line)', 'Kurskaya (Arbatsko-Pokrovskaya Line)'},
    'Begovaya': {'Ul. 1905 Goda', 'Polezhaevskaya', 'Begovaya (D1)'},
    'Begovaya (D1)': {'Begovaya', 'Testovskaya (D1)', 'Belorusskaya (D1)'},
    'Belokamennaya (MCC)': {'Rostokino (MCC)', 'Bvd. Rokossovskogo (MCC)'},
    'Belomorskaya': {'Khovrino', 'Rechoi Vokzal'},
    'Belorusskaya (D1)': {'Belorusskaya (Ring Line)', 'Belorusskaya (Zamoskvoretskaya Line)', 'Begovaya (D1)',
                          'Savelovskaya (D1)'},
    'Belorusskaya (Zamoskvoretskaya Line)': {'Belorusskaya (D1)', 'Belorusskaya (Ring Line)', 'Mayakovskaya',
                                             'Dynamo'},
    'Belorusskaya (Ring Line)': {'Belorusskaya (Zamoskvoretskaya Line)', 'Belorusskaya (D1)', 'Krasnopresnenskaya',
                                 'Novoslobodskaya'},
    'Belyaevo': {'Kaluzhskaya', 'Kon\'kovo'},
    'Beskudnikovo (D1)': {'Lianozovo (D1)', 'Degunino (D1)'},
    'Bibirevo': {'Altufyevo', 'Otradnoe'},
    'Biblioteka im. Lenina': {'Aleksandrovskiy Sad', 'Arbatskaya (Arbatsko-Pokrovskaya Line)', 'Borovitskaya',
                              'Kropotkinskaya', 'Okhotnyi Ryad'},
    'Bitsa (D2)': {'Butovo (D2)', 'Krasnyi Stroitel\' (D2)'},
    'Bitsevskiy Park': {'Novoyasenevskaya', 'Lesoparkovaya'},
    'Borisovo': {'Mar\'ino', 'Shipilovskaya'},
    'Borovitskaya': {'Biblioteka im. Lenina', 'Aleksandrovskiy Sad', 'Arbatskaya (Arbatsko-Pokrovskaya Line)',
                     'Chekhovskaya', 'Polyanka'},
    'Borovskoe Shosse': {'Novoperedelkino', 'Solntsevo'},
    'Botanicheskiy Sad': {'Botanicheskiy Sad (MCC)', 'Sviblovo', 'VDNKH'},
    'Botanicheskiy Sad (MCC)': {'Botanicheskiy Sad', 'Vladykino (MCC)', 'Rostokino (MCC)'},
    'Bratislavskaya': {'Mar\'ino', 'Lyublino'},
    'Bvd. Dmitriya Ushakova': {'Ul. Skobelevskaya', 'Ul. Gorchakova'},
    'Bvd. Dmitriya Donskogo': {'Ul. Starokachalovskaya', 'Annino'},
    'Bvd. Rokossovskogo (MCC)': {'Bvd. Rokossovskogo', 'Belokamennaya (MCC)', 'Lokomotiv (MCC)'},
    'Bvd. Rokossovskogo': {'Bvd. Rokossovskogo (MCC)', 'Cherkizovskaya'},
    'Buninskaya Alleya': {'Ul. Gorchakova'},
    'Butovo (D2)': {'Bitsa (D2)', 'Scherbinka (D2)'},
    'Butyrskaya': {'Mar\'ina Roscha', 'Fonvizinskaya'},
    'VDNKH': {'Alekseevskaya', 'Botanicheskiy Sad'},
    'Verkhnie Kotly (MCC)': {'ZIL (MCC)', 'Krymskaya (MCC)', 'Nagatinskaya'},
    'Verkhnie Likhobory': {'Seligerskaya', 'Okruzhnaya'},
    'Vladykino': {'Vladykino (MCC)', 'Otradnoe', 'Petrovsko-Razumovskaya (Serpukhovo-Timiryazevskaya Line)'},
    'Vladykino (MCC)': {'Vladykino', 'Okruzhnaya (MCC)', 'Botanicheskiy Sad (MCC)'},
    'Vodniki (D1)': {'Dolgoprudnaya (D1)', 'Khlebnikovo (D1)'},
    'Vodnyi Stadion': {'Rechoi Vokzal', 'Voikovskaya'},
    'Voikovskaya': {'Sokol', 'Vodnyi Stadion', 'Baltiyskaya (MCC)', 'Streshnevo (MCC)', 'Streshnevo (D2)'},
    'Volgogradskiy Prospekt': {'Proletarskaya', 'Tekstil\'schiki'},
    'Volzhskaya': {'Pechatniki', 'Lyublino'},
    'Volokolamskaya': {'Volokolamskaya (D2)', 'Myakinino', 'Mitino'},
    'Volokolamskaya (D2)': {'Volokolamskaya', 'Trikotazhnaya', 'Penyagino'},
    'Vorob\'yevy Gory': {'Universitet', 'Sportivnaya'},
    'Vorontsovskaya (BCC)': {'Zyuzino (BCC)', 'Novatorskaya (BCC)', 'Kaluzhskaya'},
    'Vystavochnaya': {'Delovoy Tsentr (BCC)', 'Delovoy Tsentr', 'Mezhdunarodnaya', 'Kievskaya (Filevskaya Line)'},
    'Vykhino': {'Ryazanskiy Prospekt', 'Lermontovskiy Prospekt'},
    'Govorovo': {'Ozernaya', 'Solntsevo'},
    'Grazhdanskaya (D2)': {'Krasnyi Baltiets (D2)', 'Dmitrovskaya (D2)'},
    'Davydkovo (BCC)': {'Amin\'yevskaya (BCC)', 'Kuntsevskaya (BCC)'},
    'Degunino (D1)': {'Beskudnikovo (D1)', 'Okruzhnaya (D1)'},
    'Delovoy Tsentr': {'Delovoy Tsentr (BCC)', 'Delovoy Tsentr (MCC)', 'Vystavochnaya',
                       'Park Pobedy (Solntsevskaya Line)'},
    'Delovoy Tsentr (BCC)': {'Delovoy Tsentr (MCC)', 'Delovoy Tsentr', 'Shelepikha (BCC)', 'Vystavochnaya'},
    'Delovoy Tsentr (MCC)': {'Delovoy Tsentr (BCC)', 'Delovoy Tsentr', 'Shelepikha (MCC)', 'Kutuzovskaya (MCC)',
                             'Mezhdunarodnaya'},
    'Depo (D2)': {'Pererva (D2)', 'Lyublino (D2)'},
    'Dynamo': {'Aeroport', 'Belorusskaya (Zamoskvoretskaya Line)', 'Petrovskiy Park (BCC)'},
    'Dmitrovskaya': {'Savelovskaya', 'Dmitrovskaya (D2)', 'Timiryazevskaya'},
    'Dmitrovskaya (D2)': {'Dmitrovskaya', 'Grazhdanskaya (D2)', 'Rizhskaya (D2)'},
    'Dobryninskaya': {'Serpukhovskaya', 'Oktyabrskaya (Ring Line)', 'Paveletskaya (Ring Line)'},
    'Dolgoprudnaya (D1)': {'Vodniki (D1)', 'Novodachnaya (D1)'},
    'Domodedovskaya': {'Krasnogvardeiskaya', 'Orekhovo'},
    'Dostoevskaya': {'Mar\'ina Roscha', 'Trubnaya'},
    'Dubrovka': {'Dubrovka (MCC)', 'Kozhuhovskaya', 'Krest\'yanskaya Zastava'},
    'Dubrovka (MCC)': {'Dubrovka', 'Ugreshskaya (MCC)', 'Avtozavodskaya (MCС)'},
    'Zhulebino': {'Kotel\'niki', 'Lermontovskiy Prospekt'},
    'ZIL (MCC)': {'Avtozavodskaya (MCС)', 'Verkhnie Kotly (MCC)'},
    'Zorge (MCC)': {'Panfilovskaya (MCC)', 'Khoroshevo (MCC)'},
    'Zyuzino (BCC)': {'Vorontsovskaya (BCC)', 'Kakhovskaya (BCC)'},
    'Zyablikovo': {'Shipilovskaya', 'Krasnogvardeiskaya'},
    'Izmailovo (MCC)': {'Partizanskaya', 'Sokolinaya Gora (MCC)', 'Lokomotiv (MCC)'},
    'Izmailovskaya': {'Pervomaiskaya', 'Partizanskaya'},
    'Kalanchevskaya (D2)': {'Komsomolskaya (Ring Line)', 'Komsomolskaya', 'Rizhskaya (D2)', 'Kurskaya (D2)'},
    'Kalitniki (D2)': {'Moskva-Tovarnaya (D2)', 'Novokhokhlovskaya (D2)'},
    'Kaluzhskaya': {'Belyaevo', 'Novye Cheremushki', 'Vorontsovskaya (BCC)'},
    'Kantemirovskaya': {'Tsaritsyno', 'Kashirskaya'},
    'Kakhovskaya (BCC)': {'Sevastopolskaya'},
    'Kashirskaya': {'Kantemirovskaya', 'Kolomenskaya'},
    'Kievskaya (Ring Line)': {'Kievskaya (Filevskaya Line)', 'Kievskaya (Arbatsko-Pokrovskaya Line)',
                              'Park Kul\'tury (Ring Line)', 'Krasnopresnenskaya'},
    'Kievskaya (Filevskaya Line)': {'Kievskaya (Ring Line)', 'Kievskaya (Arbatsko-Pokrovskaya Line)',
                                    'Vystavochnaya', 'Smolenskaya (Filevskaya Line)', 'Studencheskaya'},
    'Kievskaya (Arbatsko-Pokrovskaya Line)': {'Kievskaya (Filevskaya Line)', 'Kievskaya (Ring Line)',
                                              'Smolenskaya (Arbatsko-Pokrovskaya Line)',
                                              'Park Pobedy (Arbatsko-Pokrovskaya Line)'},
    'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)': {'Turgenevskaya', 'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)',
                                               'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)'},
    'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)': {'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)',
                                                       'Kuznetskiy Most',
                                                       'Taganskaya (Tagansko-Krasnopresnenskaya Line)'},
    'Kozhuhovskaya': {'Dubrovka', 'Pechatniki'},
    'Kolomenskaya': {'Kashirskaya', 'Technopark'},
    'Kommunarka': {'Ol\'khovaya'},
    'Komsomolskaya (Ring Line)': {'Komsomolskaya', 'Kurskaya (Ring Line)', 'Kalanchevskaya (D2)',
                                  'Prospekt Mira (Ring Line)'},
    'Komsomolskaya': {'Komsomolskaya (Ring Line)', 'Kalanchevskaya (D2)', 'Krasnye Vorota', 'Krasnosel\'skaya'},
    'Kon\'kovo': {'Belyaevo', 'Teplyi Stan'},
    'Koptevo (MCC)': {'Baltiyskaya (MCC)', 'Likhobory (MCC)'},
    'Kosino': {'Ul. Dmitrievskogo', 'Yugo-Vostochnaya', 'Lermontovskiy Prospekt'},
    'Kotel\'niki': {'Zhulebino'},
    'Krasnogvardeiskaya': {'Alma-Atinskaya', 'Domodedovskaya', 'Zyablikovo'},
    'Krasnogorskaya (D2)': {'Opalikha (D2)', 'Pavshino (D2)'},
    'Krasnopresnenskaya': {'Barrikadnaya', 'Kievskaya (Ring Line)', 'Belorusskaya (Ring Line)'},
    'Krasnosel\'skaya': {'Komsomolskaya', 'Sokol\'niki'},
    'Krasnye Vorota': {'Komsomolskaya', 'Chistye Prudy'},
    'Krasnyi Baltiets (D2)': {'Grazhdanskaya (D2)', 'Streshnevo (D2)'},
    'Krasnyi Stroitel\' (D2)': {'Bitsa (D2)', 'Pokrovskoe (D2)'},
    'Krest\'yanskaya Zastava': {'Dubrovka', 'Proletarskaya', 'Rimskaya'},

}
