moscow_subway = {
    'Aviamotornaya (Kalininskaya Line)': {'Shosse Entuziastov', 'Ploschad\' Il\'icha',
                                          'Aviamotornaya (Nekrasovskaya Line)'},
    'Aviamotornaya (Nekrasovskaya Line)': {'Aviamotornaya (Kalininskaya Line)', 'Lefortovo', 'Nizhegorodskaya'},
    'Avtozavodskaya': {'Paveletskaya', 'Technopark', 'Avtozavodskaya (MCС)'},
    'Avtozavodskaya (MCС)': {'Avtozavodskaya', 'Dubrovka (MCC)', 'ZIL (MCC)'},
    'Akademicheskaya': {'Leninskiy Prospekt', 'Profsoyuznaya'},
    'Aleksandrovskiy Sad': {'Biblioteka im. Lenina', 'Arbatskaya (Filevskaya Line)',
                            'Borovitskaya', 'Arbatskaya (Arbatsko-Pokrovskaya Line)'},
    'Alekseevskaya': {'Rizhskaya', 'VDNKH'},
    'Alma-Atinskaya': {'Krasnogvardeiskaya'},
    'Altufyevo': {'Bibirevo'},
    'Amin\'yevskaya (BCC)': {'Davydkovo (BCC)', 'Michurinskiy Prospekt (BCC)'},
    'Andronovka (MCC)': {'Nizhegorodskaya (MCC)', 'Shosse Entuziastov (MCC)'},
    'Anikeevka (D2)': {'Nakhabino (D2)', 'Opalikha (D2)'},
    'Annino': {'Ul. Akademika Yangelya', 'Blvd. Dmitriya Donskogo'},
    'Arbatskaya (Arbatsko-Pokrovskaya Line)': {'Borovitskaya', 'Biblioteka im. Lenina', 'Aleksandrovskiy Sad',
                                               'Ploschad\' Revolutsii', 'Smolenskaya (Arbatsko-Pokrovskaya Line)'},
    'Arbatskaya (Filevskaya Line)': {'Aleksandrovskiy Sad', 'Smolenskaya (Filevskaya Line)'},
    'Aeroport': {'Dynamo', 'Sokol'},
    'Babushkinskaya': {'Medvedkovo', 'Sviblovo'},
    'Bagrationovskaya': {'Filevskiy Park', 'Fili'},
    'Bakovka (D1)': {'Odintsovo (D1)', 'Skolkovo (D1)'},
    'Baltiyskaya (MCC)': {'Voikovskaya', 'Koptevo (MCC)', 'Streshnevo (MCC)'},
    'Barrikadnaya': {'Krasnopresnenskaya', 'Pushkinskaya', 'Ul. 1905 Goda'},
    'Baumanskaya': {'Elektrozavodskaya (Arbatsko-Pokrovskaya Line)', 'Kurskaya (Arbatsko-Pokrovskaya Line)'},
    'Begovaya': {'Ul. 1905 Goda', 'Polezhaevskaya', 'Begovaya (D1)'},
    'Begovaya (D1)': {'Begovaya', 'Testovskaya (D1)', 'Belorusskaya (D1)'},
    'Belokamennaya (MCC)': {'Rostokino (MCC)', 'Blvd. Rokossovskogo (MCC)'},
    'Belomorskaya': {'Khovrino', 'Rechoi Vokzal'},
    'Belorusskaya (D1)': {'Belorusskaya (Ring Line)', 'Belorusskaya (Zamoskvoretskaya Line)', 'Begovaya (D1)',
                          'Savelovskaya (D1)'},
    'Belorusskaya (Zamoskvoretskaya Line)': {'Belorusskaya (D1)', 'Belorusskaya (Ring Line)', 'Mayakovskaya',
                                             'Dynamo'},
    'Belorusskaya (Ring Line)': {'Belorusskaya (Zamoskvoretskaya Line)', 'Belorusskaya (D1)', 'Krasnopresnenskaya',
                                 'Novoslobodskaya'},
    'Belyaevo': {'Kaluzhskaya', 'Kon\'kovo'},
    'Beskudnikovo (D1)': {'Lianozovo (D1)', 'Degunino (D1)'},
    'Bibirevo': {'Altufyevo', 'Otradnoe'},
    'Biblioteka im. Lenina': {'Aleksandrovskiy Sad', 'Arbatskaya (Arbatsko-Pokrovskaya Line)', 'Borovitskaya',
                              'Kropotkinskaya', 'Okhotnyi Ryad'},
    'Bitsa (D2)': {'Butovo (D2)', 'Krasnyi Stroitel\' (D2)'},
    'Bitsevskiy Park': {'Novoyasenevskaya', 'Lesoparkovaya'},
    'Borisovo': {'Mar\'ino', 'Shipilovskaya'},
    'Borovitskaya': {'Biblioteka im. Lenina', 'Aleksandrovskiy Sad', 'Arbatskaya (Arbatsko-Pokrovskaya Line)',
                     'Chekhovskaya', 'Polyanka'},
    'Borovskoe Shosse': {'Novoperedelkino', 'Solntsevo'},
    'Botanicheskiy Sad': {'Botanicheskiy Sad (MCC)', 'Sviblovo', 'VDNKH'},
    'Botanicheskiy Sad (MCC)': {'Botanicheskiy Sad', 'Vladykino (MCC)', 'Rostokino (MCC)'},
    'Bratislavskaya': {'Mar\'ino', 'Lyublino'},
    'Blvd. Dmitriya Ushakova': {'Ul. Skobelevskaya', 'Ul. Gorchakova'},
    'Blvd. Dmitriya Donskogo': {'Ul. Starokachalovskaya', 'Annino'},
    'Blvd. Rokossovskogo (MCC)': {'Blvd. Rokossovskogo', 'Belokamennaya (MCC)', 'Lokomotiv (MCC)'},
    'Blvd. Rokossovskogo': {'Blvd. Rokossovskogo (MCC)', 'Cherkizovskaya'},
    'Buninskaya Alleya': {'Ul. Gorchakova'},
    'Butovo (D2)': {'Bitsa (D2)', 'Scherbinka (D2)'},
    'Butyrskaya': {'Mar\'ina Roscha', 'Fonvizinskaya'},
    'VDNKH': {'Alekseevskaya', 'Botanicheskiy Sad'},
    'Verkhnie Kotly (MCC)': {'ZIL (MCC)', 'Krymskaya (MCC)', 'Nagatinskaya'},
    'Verkhnie Likhobory': {'Seligerskaya', 'Okruzhnaya'},
    'Vladykino': {'Vladykino (MCC)', 'Otradnoe', 'Petrovsko-Razumovskaya (Serpukhovo-Timiryazevskaya Line)'},
    'Vladykino (MCC)': {'Vladykino', 'Okruzhnaya (MCC)', 'Botanicheskiy Sad (MCC)'},
    'Vodniki (D1)': {'Dolgoprudnaya (D1)', 'Khlebnikovo (D1)'},
    'Vodnyi Stadion': {'Rechoi Vokzal', 'Voikovskaya'},
    'Voikovskaya': {'Sokol', 'Vodnyi Stadion', 'Baltiyskaya (MCC)', 'Streshnevo (MCC)', 'Streshnevo (D2)'},
    'Volgogradskiy Prospekt': {'Proletarskaya', 'Tekstil\'schiki'},
    'Volzhskaya': {'Pechatniki', 'Lyublino'},
    'Volokolamskaya': {'Volokolamskaya (D2)', 'Myakinino', 'Mitino'},
    'Volokolamskaya (D2)': {'Volokolamskaya', 'Trikotazhnaya (D2)', 'Penyagino (D2)'},
    'Vorob\'yevy Gory': {'Universitet', 'Sportivnaya'},
    'Vorontsovskaya (BCC)': {'Zyuzino (BCC)', 'Novatorskaya (BCC)', 'Kaluzhskaya'},
    'Vystavochnaya': {'Delovoy Tsentr (BCC)', 'Delovoy Tsentr', 'Mezhdunarodnaya', 'Kievskaya (Filevskaya Line)',
                      'Testovskaya (D1)'},
    'Vykhino': {'Ryazanskiy Prospekt', 'Lermontovskiy Prospekt'},
    'Govorovo': {'Ozernaya', 'Solntsevo'},
    'Grazhdanskaya (D2)': {'Krasnyi Baltiets (D2)', 'Dmitrovskaya (D2)'},
    'Davydkovo (BCC)': {'Amin\'yevskaya (BCC)', 'Kuntsevskaya (BCC)'},
    'Degunino (D1)': {'Beskudnikovo (D1)', 'Okruzhnaya (D1)'},
    'Delovoy Tsentr': {'Delovoy Tsentr (BCC)', 'Delovoy Tsentr (MCC)', 'Vystavochnaya',
                       'Park Pobedy (Solntsevskaya Line)'},
    'Delovoy Tsentr (BCC)': {'Delovoy Tsentr (MCC)', 'Delovoy Tsentr', 'Shelepikha (BCC)', 'Vystavochnaya'},
    'Delovoy Tsentr (MCC)': {'Delovoy Tsentr (BCC)', 'Delovoy Tsentr', 'Shelepikha (MCC)', 'Kutuzovskaya (MCC)',
                             'Mezhdunarodnaya'},
    'Depo (D2)': {'Pererva (D2)', 'Lyublino (D2)'},
    'Dynamo': {'Aeroport', 'Belorusskaya (Zamoskvoretskaya Line)', 'Petrovskiy Park (BCC)'},
    'Dmitrovskaya': {'Savelovskaya', 'Dmitrovskaya (D2)', 'Timiryazevskaya'},
    'Dmitrovskaya (D2)': {'Dmitrovskaya', 'Grazhdanskaya (D2)', 'Rizhskaya (D2)'},
    'Dobryninskaya': {'Serpukhovskaya', 'Oktyabrskaya (Ring Line)', 'Paveletskaya (Ring Line)'},
    'Dolgoprudnaya (D1)': {'Vodniki (D1)', 'Novodachnaya (D1)'},
    'Domodedovskaya': {'Krasnogvardeiskaya', 'Orekhovo'},
    'Dostoevskaya': {'Mar\'ina Roscha', 'Trubnaya'},
    'Dubrovka': {'Dubrovka (MCC)', 'Kozhuhovskaya', 'Krest\'yanskaya Zastava'},
    'Dubrovka (MCC)': {'Dubrovka', 'Ugreshskaya (MCC)', 'Avtozavodskaya (MCС)'},
    'Zhulebino': {'Kotel\'niki', 'Lermontovskiy Prospekt'},
    'ZIL (MCC)': {'Avtozavodskaya (MCС)', 'Verkhnie Kotly (MCC)'},
    'Zorge (MCC)': {'Panfilovskaya (MCC)', 'Khoroshevo (MCC)'},
    'Zyuzino (BCC)': {'Vorontsovskaya (BCC)', 'Kakhovskaya (BCC)'},
    'Zyablikovo': {'Shipilovskaya', 'Krasnogvardeiskaya'},
    'Izmailovo (MCC)': {'Partizanskaya', 'Sokolinaya Gora (MCC)', 'Lokomotiv (MCC)'},
    'Izmailovskaya': {'Pervomaiskaya', 'Partizanskaya'},
    'Kalanchevskaya (D2)': {'Komsomolskaya (Ring Line)', 'Komsomolskaya', 'Rizhskaya (D2)', 'Kurskaya (D2)'},
    'Kalitniki (D2)': {'Moskva-Tovarnaya (D2)', 'Novokhokhlovskaya (D2)'},
    'Kaluzhskaya': {'Belyaevo', 'Novye Cheremushki', 'Vorontsovskaya (BCC)'},
    'Kantemirovskaya': {'Tsaritsyno', 'Kashirskaya'},
    'Kakhovskaya (BCC)': {'Sevastopolskaya'},
    'Kashirskaya': {'Kantemirovskaya', 'Kolomenskaya'},
    'Kievskaya (Ring Line)': {'Kievskaya (Filevskaya Line)', 'Kievskaya (Arbatsko-Pokrovskaya Line)',
                              'Park Kul\'tury (Ring Line)', 'Krasnopresnenskaya'},
    'Kievskaya (Filevskaya Line)': {'Kievskaya (Ring Line)', 'Kievskaya (Arbatsko-Pokrovskaya Line)',
                                    'Vystavochnaya', 'Smolenskaya (Filevskaya Line)', 'Studencheskaya'},
    'Kievskaya (Arbatsko-Pokrovskaya Line)': {'Kievskaya (Filevskaya Line)', 'Kievskaya (Ring Line)',
                                              'Smolenskaya (Arbatsko-Pokrovskaya Line)',
                                              'Park Pobedy (Arbatsko-Pokrovskaya Line)'},
    'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)': {'Turgenevskaya', 'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)',
                                               'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)'},
    'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)': {'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)', 'Kuznetskiy Most',
                                                       'Taganskaya'},
    'Kozhuhovskaya': {'Dubrovka', 'Pechatniki'},
    'Kolomenskaya': {'Kashirskaya', 'Technopark'},
    'Kommunarka': {'Ol\'khovaya'},
    'Komsomolskaya (Ring Line)': {'Komsomolskaya', 'Kurskaya (Ring Line)', 'Kalanchevskaya (D2)',
                                  'Prospekt Mira (Ring Line)'},
    'Komsomolskaya': {'Komsomolskaya (Ring Line)', 'Kalanchevskaya (D2)', 'Krasnye Vorota', 'Krasnosel\'skaya'},
    'Kon\'kovo': {'Belyaevo', 'Teplyi Stan'},
    'Koptevo (MCC)': {'Baltiyskaya (MCC)', 'Likhobory (MCC)'},
    'Kosino': {'Ul. Dmitrievskogo', 'Yugo-Vostochnaya', 'Lermontovskiy Prospekt'},
    'Kotel\'niki': {'Zhulebino'},
    'Krasnogvardeiskaya': {'Alma-Atinskaya', 'Domodedovskaya', 'Zyablikovo'},
    'Krasnogorskaya (D2)': {'Opalikha (D2)', 'Pavshino (D2)'},
    'Krasnopresnenskaya': {'Barrikadnaya', 'Kievskaya (Ring Line)', 'Belorusskaya (Ring Line)'},
    'Krasnosel\'skaya': {'Komsomolskaya', 'Sokol\'niki'},
    'Krasnye Vorota': {'Komsomolskaya', 'Chistye Prudy'},
    'Krasnyi Baltiets (D2)': {'Grazhdanskaya (D2)', 'Streshnevo (D2)'},
    'Krasnyi Stroitel\' (D2)': {'Bitsa (D2)', 'Pokrovskoe (D2)'},
    'Krest\'yanskaya Zastava': {'Dubrovka', 'Proletarskaya', 'Rimskaya'},
    'Kropotkinskaya': {'Biblioteka im. Lenina', 'Park Kul\'tury'},
    'Krylatskoe': {'Molodezhnaya', 'Strogino'},
    'Krymskaya (MCC)': {'Verkhnie Kotly (MCC)', 'Ploschad\' Gagarina (MCC)'},
    'Kuznetskiy Most': {'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)', 'Lubyanka', 'Pushkinskaya'},
    'Kuntsevskaya (Filevskaya Line)': {'Kuntsevskaya (D1)', 'Kuntsevskaya (BCC)', 'Pionerskaya',
                                       'Kuntsevskaya (Arbatsko-Pokrovskaya Line)'},
    'Kuntsevskaya (BCC)': {'Kuntsevskaya (Filevskaya Line)', 'Kuntsevskaya (Arbatsko-Pokrovskaya Line)',
                           'Kuntsevskaya (D1)', 'Terekhovo (BCC)', 'Davydkovo (BCC)'},
    'Kuntsevskaya (Arbatsko-Pokrovskaya Line)': {'Kuntsevskaya (BCC)', 'Kuntsevskaya (Filevskaya Line)',
                                                 'Kuntsevskaya (D1)', 'Slavyanskiy Blvd.',
                                                 'Molodezhnaya'},
    'Kuntsevskaya (D1)': {'Kuntsevskaya (Filevskaya Line)', 'Kuntsevskaya (Arbatsko-Pokrovskaya Line)',
                          'Kuntsevskaya (BCC)', 'Slavyanskiy Blvd. (D1)', 'Rabochiy Poselok (D1)'},
    'Kurskaya (Arbatsko-Pokrovskaya Line)': {'Kurskaya (Ring Line)', 'Kurskaya (D2)', 'Baumanskaya', 'Chkalovskaya',
                                             'Ploschad\' Revolutsii'},
    'Kurskaya (Ring Line)': {'Chkalovskaya', 'Kurskaya (Arbatsko-Pokrovskaya Line)', 'Kurskaya (D2)',
                             'Taganskaya (Ring Line)', 'Komsomolskaya (Ring Line)'},
    'Kurskaya (D2)': {'Chkalovskaya', 'Kurskaya (Ring Line)', 'Kurskaya (Arbatsko-Pokrovskaya Line)',
                      'Kalanchevskaya (D2)', 'Moskva-Tovarnaya (D2)'},
    'Kur\'yanovo (D2)': {'Pererva (D2)', 'Moskvorech\'ye (D2)'},
    'Kutuzovskaya (MCC)': {'Kutuzovskaya', 'Delovoy Tsentr (MCC)', 'Luzhniki (MCC)'},
    'Kutuzovskaya': {'Kutuzovskaya (MCC)', 'Studencheskaya', 'Fili'},
    'Kuz\'minki': {'Ryazanskiy Prospekt', 'Tekstil\'schiki'},
    'Leninskiy Prospekt': {'Ploschad\' Gagarina (MCC)', 'Shabolovskaya', 'Akademicheskaya'},
    'Lermontovskiy Prospekt': {'Vykhino', 'Zhulebino', 'Kosino'},
    'Lesoparkovaya': {'Bitsevskiy Park', 'Ul. Starokachalovskaya'},
    'Lefortovo': {'Aviamotornaya (Nekrasovskaya Line)', 'Elektrozavodskaya (Nekrasovskaya Line)'},
    'Lianozovo (D1)': {'Beskudnikovo (D1)', 'Mark (D1)'},
    'Likhobory (MCC)': {'Koptevo (MCC)', 'Okruzhnaya (MCC)'},
    'Lobnya (D1)': {'Sheremet\'yevskaya (D1)'},
    'Lokomotiv (MCC)': {'Izmailovo (MCC)', 'Blvd. Rokossovskogo (MCC)', 'Cherkizovskaya'},
    'Lomonosovskiy Prospekt': {'Ramenki', 'Minskaya'},
    'Lubyanka': {'Kuznetskiy Most', 'Chistye Prudy', 'Okhotnyi Ryad'},
    'Luzhniki (MCC)': {'Kutuzovskaya (MCC)', 'Sportivnaya', 'Ploschad\' Gagarina (MCC)'},
    'Lukhmanovskaya': {'Nekrasovka', 'Ul. Dmitrievskogo'},
    'Lyublino': {'Volzhskaya', 'Bratislavskaya'},
    'Lyublino (D2)': {'Depo (D2)', 'Tekstil\'schiki (D2)'},
    'Mark (D1)': {'Lianozovo (D1)', 'Novodachnaya (D1)'},
    'Marksistskaya': {'Taganskaya', 'Taganskaya (Ring Line)',
                      'Ploschad\' Il\'icha', 'Tret\'yakovskaya (Kalininskaya Line)'},
    'Mar\'ina Roscha': {'Butyrskaya', 'Dostoevskaya'},
    'Mar\'ino': {'Bratislavskaya', 'Borisovo'},
    'Mayakovskaya': {'Belorusskaya (Zamoskvoretskaya Line)', 'Tverskaya'},
    'Medvedkovo': {'Babushkinskaya'},
    'Mezhdunarodnaya': {'Delovoy Tsentr (MCC)', 'Vystavochnaya', 'Testovskaya (D1)'},
    'Mendeleevskaya': {'Novoslobodskaya', 'Tsvetnoi Blvd.', 'Savelovskaya'},
    'Minskaya': {'Lomonosovskiy Prospekt', 'Park Pobedy (Solntsevskaya Line)'},
    'Mitino': {'Pyatnitskoe Shosse', 'Volokolamskaya'},
    'Michurinskiy Prospekt (BCC)': {'Michurinskiy Prospekt', 'Amin\'yevskaya (BCC)', 'Prospekt Vernadskogo (BCC)'},
    'Michurinskiy Prospekt': {'Michurinskiy Prospekt (BCC)', 'Ozernaya', 'Ramenki'},
    'Mnevniki (BCC)': {'Terekhovo (BCC)', 'Narodnoe Opolchenie (BCC)'},
    'Molodezhnaya': {'Krylatskoe', 'Kuntsevskaya (Arbatsko-Pokrovskaya Line)'},
    'Moskva-Tovarnaya (D2)': {'Kalitniki (D2)', 'Kurskaya (D2)'},
    'Moskvorech\'ye (D2)': {'Kur\'yanovo (D2)', 'Tsaritsyno (D2)'},
    'Myakinino': {'Strogino', 'Volokolamskaya'},
    'Nagatinskaya': {'Verkhnie Kotly (MCC)', 'Tul\'skaya', 'Nagornaya'},
    'Nagornaya': {'Nagatinskaya', 'Nakhimovskiy Prospekt'},
    'Narodnoe Opolchenie (BCC)': {'Mnevniki (BCC)', 'Khoroshevskaya (BCC)'},
    'Nakhabino (D2)': {'Anikeevka (D2)'},
    'Nakhimovskiy Prospekt': {'Nagornaya', 'Sevastopolskaya'},
    'Nekrasovka': {'Lukhmanovskaya'},
    'Nemchinovka (D1)': {'Skolkovo (D1)', 'Setun\' (D1)'},
    'Nizhegorodskaya (MCC)': {'Andronovka (MCC)', 'Nizhegorodskaya', 'Novokhokhlovskaya (MCC)'},
    'Nizhegorodskaya': {'Nizhegorodskaya (MCC)', 'Stakhanovskaya', 'Aviamotornaya (Nekrasovskaya Line)'},
    'Novatorskaya (BCC)': {'Vorontsovskaya (BCC)', 'Prospekt Vernadskogo (BCC)'},
    'Novogireevo': {'Novokosino', 'Perovo'},
    'Novodachnaya (D1)': {'Mark (D1)', 'Dolgoprudnaya (D1)'},
    'Novokosino': {'Novogireevo'},
    'Novokuznetskaya': {'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)', 'Tret\'yakovskaya (Kalininskaya Line)',
                        'Paveletskaya', 'Teatral\'naya'},
    'Novoperedelkino': {'Rasskazovka', 'Borovskoe Shosse'},
    'Novoslobodskaya': {'Mendeleevskaya', 'Belorusskaya (Ring Line)', 'Prospekt Mira (Ring Line)'},
    'Novokhokhlovskaya (D2)': {'Novokhokhlovskaya (MCC)', 'Kalitniki (D2)', 'Tekstil\'schiki (D2)'},
    'Novokhokhlovskaya (MCC)': {'Novokhokhlovskaya (D2)', 'Ugreshskaya (MCC)', 'Nizhegorodskaya (MCC)'},
    'Novoyasenevskaya': {'Yasenevo', 'Bitsevskiy Park'},
    'Novye Cheremushki': {'Kaluzhskaya', 'Profsoyuznaya'},
    'Odintsovo (D1)': {'Bakovka (D1)'},
    'Ozernaya': {'Govorovo', 'Michurinskiy Prospekt'},
    'Okruzhnaya': {'Okruzhnaya (MCC)', 'Okruzhnaya (D1)', 'Verkhnie Likhobory',
                   'Petrovsko-Razumovskaya (Lyublinsko-Dmitrovskaya Line)'},
    'Okruzhnaya (MCC)': {'Okruzhnaya (D1)', 'Okruzhnaya', 'Likhobory (MCC)', 'Vladykino (MCC)'},
    'Okruzhnaya (D1)': {'Okruzhnaya (MCC)', 'Okruzhnaya', 'Degunino (D1)', 'Timiryazevskaya (D1)'},
    'Okskaya': {'Yugo-Vostochnaya', 'Stakhanovskaya'},
    'Oktyabrskaya (Ring Line)': {'Oktyabrskaya', 'Park Kul\'tury (Ring Line)', 'Dobryninskaya'},
    'Oktyabrskaya': {'Oktyabrskaya (Ring Line)', 'Shabolovskaya', 'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)'},
    'Oktyabr\'skoe Pole': {'Schukinskaya', 'Polezhaevskaya'},
    'Ol\'khovaya': {'Kommunarka', 'Prokshino'},
    'Opalikha (D2)': {'Anikeevka (D2)', 'Krasnogorskaya (D2)'},
    'Orekhovo': {'Domodedovskaya', 'Tsaritsyno'},
    'Ostaf\'yevo (D2)': {'Silikatnaya (D2)', 'Scherbinka (D2)'},
    'Otradnoe': {'Bibirevo', 'Vladykino'},
    'Okhotnyi Ryad': {'Biblioteka im. Lenina', 'Lubyanka', 'Teatral\'naya'},
    'Paveletskaya': {'Paveletskaya (Ring Line)', 'Novokuznetskaya', 'Avtozavodskaya'},
    'Paveletskaya (Ring Line)': {'Paveletskaya', 'Dobryninskaya', 'Taganskaya (Ring Line)'},
    'Pavshino (D2)': {'Penyagino (D2)', 'Krasnogorskaya (D2)'},
    'Panfilovskaya (MCC)': {'Zorge (MCC)', 'Streshnevo (MCC)'},
    'Park Kul\'tury (Ring Line)': {'Park Kul\'tury', 'Oktyabrskaya (Ring Line)',
                                   'Kievskaya (Ring Line)'},
    'Park Kul\'tury': {'Park Kul\'tury (Ring Line)', 'Kropotkinskaya', 'Frunzenskaya'},
    'Park Pobedy (Solntsevskaya Line)': {'Park Pobedy (Arbatsko-Pokrovskaya Line)', 'Delovoy Tsentr', 'Minskaya'},
    'Park Pobedy (Arbatsko-Pokrovskaya Line)': {'Park Pobedy (Solntsevskaya Line)', 'Slavyanskiy Blvd.',
                                                'Kievskaya (Arbatsko-Pokrovskaya Line)'},
    'Partizanskaya': {'Izmailovskaya', 'Izmailovo (MCC)', 'Semenovskaya'},
    'Penyagino (D2)': {'Pavshino (D2)', 'Volokolamskaya (D2)'},
    'Pervomaiskaya': {'Izmailovskaya', 'Schelkovskaya'},
    'Pererva (D2)': {'Kur\'yanovo (D2)', 'Depo (D2)'},
    'Perovo': {'Novogireevo', 'Shosse Entuziastov'},
    'Petrovskiy Park (BCC)': {'Dynamo', 'CSKA (BCC)', 'Savelovskaya (BCC)'},
    'Petrovsko-Razumovskaya (Serpukhovo-Timiryazevskaya Line)': {'Petrovsko-Razumovskaya (Lyublinsko-Dmitrovskaya'
                                                                 ' Line)', 'Vladykino', 'Timiryazevskaya'},
    'Petrovsko-Razumovskaya (Lyublinsko-Dmitrovskaya Line)': {'Fonvizinskaya', 'Okruzhnaya',
                                                              'Petrovsko-Razumovskaya (Serpukhovo-Timiryazevskaya'
                                                              ' Line)'},
    'Pechatniki': {'Kozhuhovskaya', 'Volzhskaya'},
    'Pionerskaya': {'Kuntsevskaya (Filevskaya Line)', 'Filevskiy Park'},
    'Planernaya': {'Skhodnenskaya'},
    'Ploschad\' Gagarina (MCC)': {'Luzhniki (MCC)', 'Leninskiy Prospekt', 'Krymskaya (MCC)'},
    'Ploschad\' Il\'icha': {'Marksistskaya', 'Aviamotornaya (Kalininskaya Line)', 'Rimskaya'},
    'Ploschad\' Revolutsii': {'Kurskaya (Arbatsko-Pokrovskaya Line)', 'Arbatskaya (Arbatsko-Pokrovskaya Line)',
                              'Teatral\'naya'},
    'Podol\'sk (D2)': {'Silikatnaya (D2)'},
    'Pokrovskoe (D2)': {'Krasnyi Stroitel\' (D2)', 'Tsaritsyno (D2)'},
    'Polezhaevskaya': {'Oktyabr\'skoe Pole', 'Begovaya', 'Khoroshevskaya (BCC)', 'Khoroshevo (MCC)'},
    'Polyanka': {'Borovitskaya', 'Serpukhovskaya'},
    'Prazhskaya': {'Yuzhnaya', 'Ul. Akademika Yangelya'},
    'Preobrazhenskaya Ploschad\'': {'Sokol\'niki', 'Cherkizovskaya'},
    'Prokshino': {'Ol\'khovaya', 'Filatov Lug'},
    'Proletarskaya': {'Krest\'yanskaya Zastava', 'Volgogradskiy Prospekt', 'Taganskaya'},
    'Prospekt Vernadskogo (BCC)': {'Prospekt Vernadskogo', 'Novatorskaya (BCC)', 'Michurinskiy Prospekt (BCC)'},
    'Prospekt Vernadskogo': {'Prospekt Vernadskogo (BCC)', 'Universitet', 'Yugo-Zapadnaya'},
    'Prospekt Mira (Ring Line)': {'Prospekt Mira', 'Komsomolskaya (Ring Line)', 'Novoslobodskaya'},
    'Prospekt Mira': {'Prospekt Mira (Ring Line)', 'Sukharevskaya', 'Rizhskaya'},
    'Profsoyuznaya': {'Akademicheskaya', 'Novye Cheremushki'},
    'Pushkinskaya': {'Kuznetskiy Most', 'Barrikadnaya', 'Tverskaya', 'Chekhovskaya'},
    'Pyatnitskoe Shosse': {'Mitino'},
    'Rabochiy Poselok (D1)': {'Kuntsevskaya (D1)', 'Setun\' (D1)'},
    'Ramenki': {'Michurinskiy Prospekt', 'Lomonosovskiy Prospekt'},
    'Rasskazovka': {'Novoperedelkino'},
    'Rechoi Vokzal': {'Vodnyi Stadion', 'Belomorskaya'},
    'Rizhskaya': {'Rizhskaya (D2)', 'Alekseevskaya', 'Prospekt Mira'},
    'Rizhskaya (D2)': {'Rizhskaya', 'Dmitrovskaya (D2)', 'Kalanchevskaya (D2)'},
    'Rimskaya': {'Ploschad\' Il\'icha', 'Krest\'yanskaya Zastava', 'Chkalovskaya'},
    'Rostokino (MCC)': {'Botanicheskiy Sad (MCC)', 'Belokamennaya (MCC)'},
    'Rumyantsevo': {'Salar\'yevo', 'Troparevo'},
    'Ryazanskiy Prospekt': {'Vykhino', 'Kuz\'minki'},
    'Savelovskaya (D1)': {'Savelovskaya (BCC)', 'Belorusskaya (D1)', 'Timiryazevskaya (D1)'},
    'Savelovskaya (BCC)': {'Savelovskaya', 'Savelovskaya (D1)', 'Petrovskiy Park (BCC)'},
    'Savelovskaya': {'Savelovskaya (BCC)', 'Mendeleevskaya', 'Dmitrovskaya'},
    'Salar\'yevo': {'Rumyantsevo', 'Filatov Lug'},
    'Sviblovo': {'Botanicheskiy Sad', 'Babushkinskaya'},
    'Sevastopolskaya': {'Nakhimovskiy Prospekt', 'Kakhovskaya (BCC)', 'Chertanovskaya'},
    'Seligerskaya': {'Verkhnie Likhobory'},
    'Semenovskaya': {'Partizanskaya', 'Elektrozavodskaya (Arbatsko-Pokrovskaya Line)'},
    'Serpukhovskaya': {'Polyanka', 'Dobryninskaya', 'Tul\'skaya'},
    'Setun\' (D1)': {'Rabochiy Poselok (D1)', 'Nemchinovka (D1)'},
    'Silikatnaya (D2)': {'Podol\'sk (D2)', 'Ostaf\'yevo (D2)'},
    'Skolkovo (D1)': {'Nemchinovka (D1)', 'Bakovka (D1)'},
    'Slavyanskiy Blvd. (D1)': {'Slavyanskiy Blvd.', 'Kuntsevskaya (D1)', 'Fili (D1)'},
    'Slavyanskiy Blvd.': {'Slavyanskiy Blvd. (D1)', 'Park Pobedy (Arbatsko-Pokrovskaya Line)',
                          'Kuntsevskaya (Arbatsko-Pokrovskaya Line)'},
    'Smolenskaya (Arbatsko-Pokrovskaya Line)': {'Kievskaya (Arbatsko-Pokrovskaya Line)',
                                                'Arbatskaya (Arbatsko-Pokrovskaya Line)'},
    'Smolenskaya (Filevskaya Line)': {'Kievskaya (Filevskaya Line)', 'Arbatskaya (Filevskaya Line)'},
    'Sokol': {'Aeroport', 'Voikovskaya'},
    'Sokolinaya Gora (MCC)': {'Izmailovo (MCC)', 'Shosse Entuziastov (MCC)'},
    'Sokol\'niki': {'Krasnosel\'skaya', 'Preobrazhenskaya Ploschad\''},
    'Solntsevo': {'Govorovo', 'Borovskoe Shosse'},
    'Spartak': {'Schukinskaya', 'Tushinskaya'},
    'Sportivnaya': {'Luzhniki (MCC)', 'Vorob\'yevy Gory', 'Frunzenskaya'},
    'Sretenskiy Blvd.': {'Turgenevskaya', 'Chistye Prudy', 'Trubnaya', 'Chkalovskaya'},
    'Stakhanovskaya': {'Nizhegorodskaya', 'Okskaya'},
    'Streshnevo (MCC)': {'Streshnevo (D2)', 'Panfilovskaya (MCC)', 'Baltiyskaya (MCC)'},
    'Streshnevo (D2)': {'Streshnevo (MCC)', 'Schukinskaya (D2)', 'Krasnyi Baltiets (D2)'},
    'Strogino': {'Myakinino', 'Krylatskoe'},
    'Studencheskaya': {'Kutuzovskaya', 'Kievskaya (Filevskaya Line)'},
    'Sukharevskaya': {'Prospekt Mira', 'Turgenevskaya'},
    'Skhodnenskaya': {'Planernaya', 'Tushinskaya'},
    'Teplyi Stan': {'Kon\'kovo', 'Yasenevo'},
    'Taganskaya': {'Taganskaya (Ring Line)', 'Proletarskaya', 'Kitai-Gorod (Tagansko-Krasnopresnenskaya Line)',
                   'Marksistskaya'},
    'Taganskaya (Ring Line)': {'Taganskaya', 'Paveletskaya (Ring Line)', 'Marksistskaya', 'Kurskaya (Ring Line)'},
    'Tverskaya': {'Pushkinskaya', 'Mayakovskaya', 'Chekhovskaya', 'Teatral\'naya'},
    'Teatral\'naya': {'Tverskaya', 'Ploschad\' Revolutsii', 'Okhotnyi Ryad', 'Novokuznetskaya'},
    'Tekstil\'schiki': {'Volgogradskiy Prospekt', 'Tekstil\'schiki (D2)', 'Kuz\'minki'},
    'Tekstil\'schiki (D2)': {'Tekstil\'schiki', 'Novokhokhlovskaya (D2)', 'Lyublino (D2)'},
    'Terekhovo (BCC)': {'Mnevniki (BCC)', 'Kuntsevskaya (BCC)'},
    'Testovskaya (D1)': {'Begovaya (D1)', 'Fili (D1)', 'Vystavochnaya', 'Mezhdunarodnaya', 'Shelepikha (BCC)'},
    'Technopark': {'Kolomenskaya', 'Avtozavodskaya'},
    'Timiryazevskaya': {'Timiryazevskaya (D1)', 'Petrovsko-Razumovskaya (Serpukhovo-Timiryazevskaya Line)',
                        'Dmitrovskaya'},
    'Timiryazevskaya (D1)': {'Timiryazevskaya', 'Okruzhnaya (D1)', 'Savelovskaya (D1)'},
    'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)': {'Tret\'yakovskaya (Kalininskaya Line)', 'Novokuznetskaya',
                                                    'Oktyabrskaya', 'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)'},
    'Tret\'yakovskaya (Kalininskaya Line)': {'Tret\'yakovskaya (Kaluzhsko-Rizhskaya Line)', 'Novokuznetskaya',
                                             'Marksistskaya'},
    'Trikotazhnaya (D2)': {'Volokolamskaya (D2)', 'Tushinskaya (D2)'},
    'Troparevo': {'Rumyantsevo', 'Yugo-Zapadnaya'},
    'Trubnaya': {'Dostoevskaya', 'Tsvetnoi Blvd.', 'Sretenskiy Blvd.'},
    'Tul\'skaya': {'Serpukhovskaya', 'Nagatinskaya'},
    'Turgenevskaya': {'Sukharevskaya', 'Sretenskiy Blvd.', 'Kitai-Gorod (Kaluzhsko-Rizhskaya Line)', 'Chistye Prudy'},
    'Tushinskaya': {'Tushinskaya (D2)', 'Skhodnenskaya', 'Spartak'},
    'Tushinskaya (D2)': {'Trikotazhnaya (D2)', 'Tushinskaya', 'Schukinskaya (D2)'},
    'Ugreshskaya (MCC)': {'Novokhokhlovskaya (MCC)', 'Dubrovka (MCC)'},
    'Ul. 1905 Goda': {'Barrikadnaya', 'Begovaya'},
    'Ul. Akademika Yangelya': {'Annino', 'Prazhskaya'},
    'Ul. Gorchakova': {'Buninskaya Alleya', 'Blvd. Dmitriya Ushakova'},
    'Ul. Dmitrievskogo': {'Kosino', 'Lukhmanovskaya'},
    'Ul. Skobelevskaya': {'Blvd. Dmitriya Ushakova', 'Ul. Starokachalovskaya'},
    'Ul. Starokachalovskaya': {'Ul. Skobelevskaya', 'Lesoparkovaya', 'Blvd. Dmitriya Donskogo'},
    'Universitet': {'Prospekt Vernadskogo', 'Vorob\'yevy Gory'},
    'Filevskiy Park': {'Pionerskaya', 'Bagrationovskaya'},
    'Filatov Lug': {'Salar\'yevo', 'Prokshino'},
    'Fili': {'Fili (D1)', 'Bagrationovskaya', 'Kutuzovskaya'},
    'Fili (D1)': {'Fili', 'Testovskaya (D1)', 'Slavyanskiy Blvd. (D1)'},
    'Fonvizinskaya': {'Petrovsko-Razumovskaya (Lyublinsko-Dmitrovskaya Line)', 'Butyrskaya'},
    'Frunzenskaya': {'Sportivnaya', 'Park Kul\'tury'},
    'Khlebnikovo (D1)': {'Vodniki (D1)', 'Sheremet\'yevskaya (D1)'},
    'Khovrino': {'Belomorskaya'},
    'Khoroshevo (MCC)': {'Shelepikha (MCC)', 'Zorge (MCC)', 'Polezhaevskaya', 'Khoroshevskaya (BCC)'},
    'Khoroshevskaya (BCC)': {'Khoroshevo (MCC)', 'Polezhaevskaya', 'CSKA (BCC)', 'Shelepikha (BCC)',
                             'Narodnoe Opolchenie (BCC)'},
    'Tsaritsyno': {'Tsaritsyno (D2)', 'Orekhovo', 'Kantemirovskaya'},
    'Tsaritsyno (D2)': {'Tsaritsyno', 'Pokrovskoe (D2)', 'Moskvorech\'ye (D2)'},
    'Tsvetnoi Blvd.': {'Trubnaya', 'Mendeleevskaya', 'Chekhovskaya'},
    'CSKA (BCC)': {'Petrovskiy Park (BCC)', 'Khoroshevskaya (BCC)'},
    'Cherkizovskaya': {'Preobrazhenskaya Ploschad\'', 'Lokomotiv (MCC)', 'Blvd. Rokossovskogo'},
    'Chertanovskaya': {'Sevastopolskaya', 'Yuzhnaya'},
    'Chekhovskaya': {'Tsvetnoi Blvd.', 'Tverskaya', 'Borovitskaya', 'Pushkinskaya'},
    'Chistye Prudy': {'Turgenevskaya', 'Sretenskiy Blvd.', 'Lubyanka', 'Krasnye Vorota'},
    'Chkalovskaya': {'Sretenskiy Blvd.', 'Rimskaya', 'Kurskaya (Arbatsko-Pokrovskaya Line)', 'Kurskaya (D2)',
                     'Kurskaya (Ring Line)'},
    'Shabolovskaya': {'Oktyabrskaya', 'Leninskiy Prospekt'},
    'Shelepikha (BCC)': {'Shelepikha (MCC)', 'Testovskaya (D1)', 'Delovoy Tsentr (BCC)', 'Khoroshevskaya (BCC)'},
    'Shelepikha (MCC)': {'Shelepikha (BCC)', 'Delovoy Tsentr (MCC)', 'Khoroshevo (MCC)'},
    'Sheremet\'yevskaya (D1)': {'Khlebnikovo (D1)', 'Lobnya (D1)'},
    'Shipilovskaya': {'Borisovo', 'Zyablikovo'},
    'Shosse Entuziastov': {'Shosse Entuziastov (MCC)', 'Perovo', 'Aviamotornaya (Kalininskaya Line)'},
    'Shosse Entuziastov (MCC)': {'Shosse Entuziastov', 'Sokolinaya Gora (MCC)', 'Andronovka (MCC)'},
    'Schelkovskaya': {'Pervomaiskaya'},
    'Scherbinka (D2)': {'Ostaf\'yevo (D2)', 'Butovo (D2)'},
    'Schukinskaya': {'Schukinskaya (D2)', 'Spartak', 'Oktyabr\'skoe Pole'},
    'Schukinskaya (D2)': {'Schukinskaya', 'Tushinskaya (D2)', 'Streshnevo (D2)'},
    'Elektrozavodskaya (Nekrasovskaya Line)': {'Elektrozavodskaya (Arbatsko-Pokrovskaya Line)', 'Lefortovo'},
    'Elektrozavodskaya (Arbatsko-Pokrovskaya Line)': {'Elektrozavodskaya (Nekrasovskaya Line)', 'Semenovskaya',
                                                      'Baumanskaya'},
    'Yugo-Vostochnaya': {'Okskaya', 'Kosino'},
    'Yugo-Zapadnaya': {'Troparevo', 'Prospekt Vernadskogo'},
    'Yuzhnaya': {'Prazhskaya', 'Chertanovskaya'},
    'Yasenevo': {'Teplyi Stan', 'Novoyasenevskaya'}
}
